#!/usr/bin/env ruby

raise 'Missing argument: Filename' if ARGV.empty?

require 'date'

post_title = ARGV.join(' ')
post_date = Date.today.to_s
post_time = '09:00:00 -04:00'
file_path = "./_posts/#{post_date}-#{ARGV.join('-').gsub(/:/, "").downcase}.md"

raise 'File already exists' if File.exist? file_path

front_matter = <<~FRONTMATTER
---
layout: post
title: #{post_title.gsub(/:/, "&#58;")}
date: #{post_date}
categories: post
permalink: /:title/
image: /assets/oscar.jpg
---
FRONTMATTER

File.open file_path, "w+" do |file|
  file.puts front_matter
end

puts "Succesfully created #{file_path}!"